version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: gunicorn -b :8000 --reload app.wsgi
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
